---
- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers
  vars:
    postgres_service: postgresql-10.service
    postgres_port: 5432
    postgres_user: postgres
    postgres_users:
      - name: flask
        password: redhat
        database: flask_db
        state: present
        priv: ALL
    postgres_databases:
      - name: flask_db
        owner: flask
      - name: books_store
        owner: flask

  roles:

    - postgres
